recipe: default.v1
assistant_id: chatbot-lite
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 30
  - name: FallbackClassifier
    threshold: 0.5

policies:
  - name: RulePolicy
